# Generated by Django 2.1.2 on 2019-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190113_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
