# Generated by Django 2.1.2 on 2019-03-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190302_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfav',
            options={},
        ),
    ]
