# Generated by Django 2.2.1 on 2019-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190302_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomSim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank1', models.IntegerField()),
                ('rank2', models.IntegerField()),
                ('rank3', models.IntegerField()),
                ('rank4', models.IntegerField()),
                ('rank5', models.IntegerField()),
                ('rank6', models.IntegerField()),
                ('rank7', models.IntegerField()),
                ('rank8', models.IntegerField()),
                ('rank9', models.IntegerField()),
                ('rank10', models.FloatField()),
                ('score1', models.FloatField()),
                ('score2', models.FloatField()),
                ('score3', models.FloatField()),
                ('score4', models.FloatField()),
                ('score5', models.FloatField()),
                ('score6', models.FloatField()),
                ('score7', models.FloatField()),
                ('score8', models.FloatField()),
                ('score9', models.FloatField()),
                ('score10', models.FloatField()),
            ],
            options={
                'db_table': 'similality',
            },
        ),
    ]
