# Generated by Django 2.2.1 on 2019-06-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_recomsim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomsim',
            options={'managed': False},
        ),
    ]
