# Generated by Django 2.2.1 on 2019-06-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190604_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreJN',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Post')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RecomSim')),
            ],
            options={
                'unique_together': {('id', 'rank')},
            },
        ),
    ]
