# Generated by Django 2.2.1 on 2019-06-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_scorejn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreJN',
        ),
    ]
