# Generated by Django 2.1.2 on 2019-03-01 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190302_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfav',
            name='fav_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postfav',
            name='fav_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postfav',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
