# Generated by Django 2.1.2 on 2019-03-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190302_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfav',
            options={'managed': False},
        ),
    ]
